export const CREATE_STUDENT = 'CREATE_STUDENT';
export const GET_STUDENTS = 'GET_STUDENTS';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const SET_ERROR = 'SET_ERROR';

export const REMOVE_DELETED_STUDENT= 'REMOVE_DELETED_STUDENT';
